// Code generated by Arduino IoT Cloud, DO NOT EDIT.
 
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
 
 
const char THING_ID[]           = "3b2c44f9-e11e-4bea-9d37-e1ac566f55d3";
const char DEVICE_LOGIN_NAME[]  = "772ae50b-9678-465c-96c6-fa7c7d0d9aad";
 
const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password
 
void onLEDChange();
 
CloudLight lED;
CloudAngle x;
CloudAngle y;
CloudAngle z;
 
void initProperties(){
 
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(lED, READWRITE, ON_CHANGE, onLEDChange);
  ArduinoCloud.addProperty(x, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(y, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(z, READ, ON_CHANGE, NULL);
 
}
 
WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);