#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://cloud.arduino.cc/ 
 
  Arduino IoT Cloud Variables description
 
  The following variables are automatically generated and updated when changes are made to the Thing
 
  CloudLight lED;
  CloudAngle x;
  CloudAngle y;
  CloudAngle z;
 
  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/
 
#include "thingProperties.h"
#include<Wire.h>
 
const int MPU_addr=0x68;
int16_t AcX,AcY,AcZ,Tmp,GyX,GyY,GyZ;
 
int minVal=265;
int maxVal=402;
 
double X;
double Y;
double Z;
 
void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  pinMode (0, OUTPUT);
  Wire.begin();
  Wire.beginTransmission(MPU_addr);
  Wire.write(0x6B);
  Wire.write(0);
  Wire.endTransmission(true);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
 
  // Defined in thingProperties.h
  initProperties();
 
  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}
 
void loop() {
  ArduinoCloud.update();
  MPU6050_Read();
  // Your code here 
  
  
}
 
void onLEDChange() {
  if (lED == 1)
  {
   digitalWrite (0, HIGH);
  }
  else
  {
    digitalWrite (0, LOW);
  }
  // Do something
}
 
void MPU6050_Read()
{
  Wire.beginTransmission(MPU_addr);
  Wire.write(0x3B);
  Wire.endTransmission(false);
  Wire.requestFrom(MPU_addr,14,true);
  AcX=Wire.read()<<8|Wire.read();
  AcY=Wire.read()<<8|Wire.read();
  AcZ=Wire.read()<<8|Wire.read();
  int xAng = map(AcX,minVal,maxVal,-90,90);
  int yAng = map(AcY,minVal,maxVal,-90,90);
  int zAng = map(AcZ,minVal,maxVal,-90,90);
 
  X= RAD_TO_DEG * (atan2(-yAng, -zAng)+PI);
  Y= RAD_TO_DEG * (atan2(-xAng, -zAng)+PI);
  Z= RAD_TO_DEG * (atan2(-yAng, -xAng)+PI);
  
  x=X;
  y=Y;
  z=Z;
 
  Serial.print("AngleX= ");
  Serial.println(X);
 
  Serial.print("AngleY= ");
  Serial.println(Y);
 
  Serial.print("AngleZ= ");
  Serial.println(Z);
  Serial.println("-----------------------------------------");
}